"""
Named multigradient theme presets for Design System V1.

Each preset defines a full token set plus abstract gradient wash parameters.
Background PNGs are generated by scripts/generate_theme_backgrounds.py.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

DEFAULT_PRESET_ID = "default"

# (center_x_ratio, center_y_ratio, radius_ratio, rgb, opacity)
GradientWash = tuple[float, float, float, tuple[int, int, int], float]


@dataclass(frozen=True)
class ThemePreset:
    id: str
    label: str
    window_bg: str
    surface_bg: str
    input_bg: str
    border: str
    accent: str
    accent_hover: str
    accent_alt: str
    text_primary: str
    text_secondary: str
    sidebar_tile_active: str
    status_bar_bg: str
    card_shadow: str
    app_primary_text: str
    gradient_base: tuple[int, int, int]
    gradient_washes: tuple[GradientWash, ...] = field(default_factory=tuple)
    sidebar_bg: Optional[str] = None

    @property
    def sidebar_surface(self) -> str:
        return self.sidebar_bg or self.surface_bg


THEME_PRESETS: dict[str, ThemePreset] = {}


def _register(preset: ThemePreset) -> ThemePreset:
    THEME_PRESETS[preset.id] = preset
    return preset


_register(ThemePreset(
    id="default",
    label="Default (Cyan)",
    window_bg="#1a1d24",
    surface_bg="#222731",
    input_bg="#1e222b",
    border="#2f3645",
    accent="#00f2fe",
    accent_hover="#14d9ff",
    accent_alt="#4facfe",
    text_primary="#f3f6fb",
    text_secondary="#8a95a5",
    sidebar_tile_active="#293140",
    status_bar_bg="#16242c",
    card_shadow="#1d222b",
    app_primary_text="#0a1218",
    gradient_base=(26, 29, 36),
    gradient_washes=(
        (0.25, 0.35, 0.55, (0, 180, 220), 0.18),
        (0.75, 0.65, 0.45, (40, 80, 140), 0.14),
        (0.55, 0.15, 0.35, (20, 60, 90), 0.10),
    ),
))

_register(ThemePreset(
    id="midnight_aurora",
    label="Midnight Aurora",
    window_bg="#12141f",
    surface_bg="#1a1d2e",
    input_bg="#161825",
    border="#2a2f45",
    accent="#7c8cff",
    accent_hover="#96a0ff",
    accent_alt="#5b6fd6",
    text_primary="#eef0ff",
    text_secondary="#8b90b0",
    sidebar_tile_active="#242840",
    status_bar_bg="#0f111a",
    card_shadow="#141622",
    app_primary_text="#0c0e18",
    gradient_base=(18, 20, 31),
    gradient_washes=(
        (0.20, 0.30, 0.60, (90, 70, 200), 0.22),
        (0.80, 0.70, 0.50, (40, 120, 180), 0.16),
        (0.50, 0.85, 0.40, (60, 40, 120), 0.12),
    ),
))

_register(ThemePreset(
    id="ember_dusk",
    label="Ember Dusk",
    window_bg="#1a1412",
    surface_bg="#241c18",
    input_bg="#1e1815",
    border="#3a2e28",
    accent="#f97316",
    accent_hover="#fb923c",
    accent_alt="#ea580c",
    text_primary="#faf0ea",
    text_secondary="#a89488",
    sidebar_tile_active="#2e2420",
    status_bar_bg="#140f0d",
    card_shadow="#1c1614",
    app_primary_text="#1a0e08",
    gradient_base=(26, 20, 18),
    gradient_washes=(
        (0.30, 0.40, 0.55, (200, 80, 30), 0.20),
        (0.75, 0.25, 0.45, (140, 40, 20), 0.15),
        (0.60, 0.75, 0.35, (80, 30, 15), 0.10),
    ),
))

_register(ThemePreset(
    id="forest_depth",
    label="Forest Depth",
    window_bg="#101814",
    surface_bg="#182420",
    input_bg="#141e1a",
    border="#283830",
    accent="#34d399",
    accent_hover="#4ade80",
    accent_alt="#059669",
    text_primary="#ecfdf5",
    text_secondary="#86a898",
    sidebar_tile_active="#1e2c26",
    status_bar_bg="#0c1210",
    card_shadow="#121a16",
    app_primary_text="#061410",
    gradient_base=(16, 24, 20),
    gradient_washes=(
        (0.25, 0.55, 0.50, (20, 120, 80), 0.18),
        (0.70, 0.30, 0.45, (10, 80, 60), 0.14),
        (0.85, 0.80, 0.30, (30, 60, 40), 0.10),
    ),
))

_register(ThemePreset(
    id="ocean_void",
    label="Ocean Void",
    window_bg="#0c1218",
    surface_bg="#141c26",
    input_bg="#101820",
    border="#243040",
    accent="#38bdf8",
    accent_hover="#5cc8fa",
    accent_alt="#0284c7",
    text_primary="#e8f4fc",
    text_secondary="#7a94a8",
    sidebar_tile_active="#1a2838",
    status_bar_bg="#080e14",
    card_shadow="#101820",
    app_primary_text="#041018",
    gradient_base=(12, 18, 24),
    gradient_washes=(
        (0.35, 0.45, 0.55, (20, 100, 180), 0.20),
        (0.80, 0.60, 0.40, (10, 60, 120), 0.14),
        (0.15, 0.75, 0.35, (30, 80, 140), 0.10),
    ),
))

_register(ThemePreset(
    id="violet_haze",
    label="Violet Haze",
    window_bg="#14121c",
    surface_bg="#1e1a28",
    input_bg="#181622",
    border="#322e42",
    accent="#a78bfa",
    accent_hover="#b9a0fc",
    accent_alt="#7c3aed",
    text_primary="#f3f0ff",
    text_secondary="#9a92b0",
    sidebar_tile_active="#28243a",
    status_bar_bg="#0e0c14",
    card_shadow="#16141e",
    app_primary_text="#100818",
    gradient_base=(20, 18, 28),
    gradient_washes=(
        (0.40, 0.35, 0.55, (120, 60, 200), 0.22),
        (0.75, 0.70, 0.45, (80, 40, 140), 0.16),
        (0.20, 0.80, 0.35, (60, 30, 100), 0.10),
    ),
))

_register(ThemePreset(
    id="slate_mono",
    label="Slate Mono",
    window_bg="#181a1e",
    surface_bg="#222428",
    input_bg="#1c1e22",
    border="#343840",
    accent="#94a3b8",
    accent_hover="#b0bcc8",
    accent_alt="#64748b",
    text_primary="#f1f5f9",
    text_secondary="#8892a0",
    sidebar_tile_active="#2a2e34",
    status_bar_bg="#121418",
    card_shadow="#1a1c20",
    app_primary_text="#0e1014",
    gradient_base=(24, 26, 30),
    gradient_washes=(
        (0.30, 0.40, 0.50, (80, 90, 110), 0.14),
        (0.70, 0.65, 0.40, (60, 70, 85), 0.10),
        (0.50, 0.20, 0.35, (50, 55, 65), 0.08),
    ),
))

_register(ThemePreset(
    id="copper_night",
    label="Copper Night",
    window_bg="#181412",
    surface_bg="#221e1a",
    input_bg="#1c1816",
    border="#383028",
    accent="#d4a574",
    accent_hover="#e0b888",
    accent_alt="#b8864a",
    text_primary="#faf6f0",
    text_secondary="#a89888",
    sidebar_tile_active="#2c2620",
    status_bar_bg="#100e0c",
    card_shadow="#1a1614",
    app_primary_text="#181008",
    gradient_base=(24, 20, 18),
    gradient_washes=(
        (0.35, 0.50, 0.50, (180, 120, 60), 0.18),
        (0.75, 0.30, 0.40, (120, 80, 40), 0.14),
        (0.60, 0.85, 0.30, (80, 50, 25), 0.10),
    ),
))

_register(ThemePreset(
    id="arctic_glow",
    label="Arctic Glow",
    window_bg="#121618",
    surface_bg="#1a2024",
    input_bg="#161c20",
    border="#2a343c",
    accent="#67e8f9",
    accent_hover="#7eedfb",
    accent_alt="#22d3ee",
    text_primary="#f0fafc",
    text_secondary="#88a0a8",
    sidebar_tile_active="#222c32",
    status_bar_bg="#0c1014",
    card_shadow="#141a1e",
    app_primary_text="#081418",
    gradient_base=(18, 22, 24),
    gradient_washes=(
        (0.30, 0.35, 0.55, (80, 180, 200), 0.18),
        (0.80, 0.65, 0.45, (60, 140, 170), 0.14),
        (0.50, 0.85, 0.35, (40, 100, 130), 0.10),
    ),
))

_register(ThemePreset(
    id="rose_shadow",
    label="Rose Shadow",
    window_bg="#181416",
    surface_bg="#221c20",
    input_bg="#1c181a",
    border="#382e34",
    accent="#f472b6",
    accent_hover="#f687c0",
    accent_alt="#db2777",
    text_primary="#fdf2f8",
    text_secondary="#a89098",
    sidebar_tile_active="#2c2428",
    status_bar_bg="#100c0e",
    card_shadow="#1a1618",
    app_primary_text="#180810",
    gradient_base=(24, 20, 22),
    gradient_washes=(
        (0.35, 0.40, 0.50, (180, 60, 120), 0.18),
        (0.75, 0.70, 0.40, (120, 40, 80), 0.14),
        (0.20, 0.75, 0.35, (80, 30, 50), 0.10),
    ),
))

_register(ThemePreset(
    id="nebula_drift",
    label="Nebula Drift",
    window_bg="#100e18",
    surface_bg="#1a1624",
    input_bg="#141220",
    border="#302a40",
    accent="#e879f9",
    accent_hover="#ee8ffb",
    accent_alt="#c026d3",
    text_primary="#faf5ff",
    text_secondary="#9888a8",
    sidebar_tile_active="#262030",
    status_bar_bg="#0a0810",
    card_shadow="#12101a",
    app_primary_text="#100818",
    gradient_base=(16, 14, 24),
    gradient_washes=(
        (0.25, 0.45, 0.55, (140, 60, 200), 0.20),
        (0.70, 0.35, 0.45, (60, 100, 200), 0.16),
        (0.85, 0.75, 0.35, (100, 40, 140), 0.12),
    ),
))

THEME_PRESET_IDS = tuple(THEME_PRESETS.keys())
THEME_PRESET_LABELS = {p.id: p.label for p in THEME_PRESETS.values()}


def preset_label(preset_id: str) -> str:
    return THEME_PRESET_LABELS.get(preset_id, THEME_PRESET_LABELS[DEFAULT_PRESET_ID])


def normalize_preset_id(value: str | None) -> str:
    if value and value in THEME_PRESETS:
        return value
    return DEFAULT_PRESET_ID


def preset_menu_values() -> list[str]:
    """Display labels for Settings dropdown (label → id resolved on save)."""
    return [p.label for p in THEME_PRESETS.values()]


def preset_id_from_label(label: str) -> str:
    for pid, plabel in THEME_PRESET_LABELS.items():
        if plabel == label:
            return pid
    return DEFAULT_PRESET_ID
